import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import Footer from "./component/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import MainPage from "@/utils/MainPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Khoojo Rooms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <MainPage>
        <ClerkProvider>
          <html lang="en">
            <body className={inter.className}>
            <Toaster
              position="top-center"
              reverseOrder={false}
            />
              <Navbar />
              {children}
              
              </body>
          </html>
        </ClerkProvider>
    </MainPage>
  );
}
